const storySegments = [{ id: 1, text: "You’re hiking in the Pacific Northwest, enjoying the fresh air and towering trees. As you climb over a rocky ridge, your foot slips, and you tumble into a hidden cave. Inside, a faint glow catches your eye. You brush away the dirt and find a crystal pendant with strange, glowing runes carved into it. The air hums with energy as you pick it up. Suddenly, the cave walls shimmer, and a portal opens in front of you. Do you step through the portal to see where it leads, or do you examine the pendant more closely before deciding?", choice1: "Step through the portal", choice1Next: 2, choice2: "Examine the pendant", choice2Next: 3, isEnding: false, image: "artifact-discovery.jpg" },
    { id: 2, text: "You step through the portal and feel a rush of warm air. You’re standing on a sandy beach in the Pacific Ocean, with turquoise waves crashing nearby. Ancient ruins rise from the water—towers of coral and stone, shimmering with a faint blue light. A voice echoes in your mind: 'Welcome, seeker, to the echoes of Atlantis.' A figure in a flowing robe approaches, holding a staff. 'I am Kael, a guardian of this lost city. We need your help to unlock its secrets.' Do you agree to help Kael, or do you explore the ruins on your own?", choice1: "Help Kael", choice1Next: 4, choice2: "Explore on your own", choice2Next: 5, isEnding: false, image: "atlantis-ruins.jpg" },
    { id: 3, text: "You decide to examine the pendant more closely. The runes glow brighter as you touch them, and a map appears in your mind—a path across the globe to the Himalayas. The pendant hums, urging you to follow the map. You leave the cave and catch a flight to the snowy mountains of Tibet. After days of hiking, you find a hidden monastery carved into the cliffs. A monk greets you, saying, 'The pendant chose you to find Lemuria’s legacy.' Do you enter the monastery to learn more, or continue hiking to search for clues on your own?", choice1: "Enter the monastery", choice1Next: 6, choice2: "Continue hiking", choice2Next: 7, isEnding: false, image: "pendant-map.jpg" },
    { id: 4, text: "You agree to help Kael, and he leads you to a sunken temple in the ocean. Inside, you find a glowing orb on a pedestal. Kael explains, 'This orb holds the memories of Atlantis. To unlock it, we must solve a puzzle.' He shows you a stone tablet with symbols matching the pendant’s runes. Together, you arrange the symbols, and the orb hums to life, projecting a map to Agartha, a hidden world inside the Earth. Kael says, 'We must go there to protect Atlantis’s legacy.' Do you travel to Agartha with Kael, or take the orb and go alone?", choice1: "Travel with Kael", choice1Next: 8, choice2: "Take the orb and go alone", choice2Next: 9, isEnding: false, image: "atlantis-temple.jpg" },
    { id: 5, text: "You decide to explore the ruins on your own. As you wander through the coral towers, you find a hidden chamber filled with golden artifacts. A holographic figure appears—a woman in ancient robes. 'I am Lira, a priestess of Atlantis. These treasures hold our history, but they are not safe here.' She offers to guide you to a safe place to preserve them. Do you follow Lira’s guidance, or collect some artifacts and return home to share your discovery?", choice1: "Follow Lira", choice1Next: 10, choice2: "Return home", choice2Next: 16, isEnding: false, image: "atlantis-ruins.jpg" },
    { id: 6, text: "You enter the monastery, and the monk introduces himself as Tenzin. He explains that Lemuria was a peaceful civilization that sank beneath the Indian Ocean long ago. The pendant is a key to finding their lost city. Tenzin offers to teach you an ancient chant to activate the pendant’s power. After hours of practice, the pendant glows, opening a portal to Lemuria’s ruins. Do you step through to explore Lemuria, or ask Tenzin to come with you for guidance?", choice1: "Explore Lemuria alone", choice1Next: 11, choice2: "Ask Tenzin to come", choice2Next: 12, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 7, text: "You continue hiking through the Himalayas, following the pendant’s map. After a tough climb, you stumble upon a cave entrance guarded by a stone statue of a serpent. The pendant glows, and the statue moves aside, revealing a tunnel. The air inside is warm and smells of the ocean. You realize this might lead to Lemuria. Do you enter the tunnel, or camp outside to prepare before going in?", choice1: "Enter the tunnel", choice1Next: 13, choice2: "Camp and prepare", choice2Next: 14, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 8, text: "You and Kael travel to Agartha through a shimmering portal. You emerge in a vast underground world lit by glowing crystals. A city of golden spires stretches before you, filled with people who look like they’re from ancient times. Kael says, 'This is Agartha, where Atlantis and Lemuria’s survivors came together. We must decide what to do with the orb’s knowledge.' Do you suggest sharing it with the surface world, or keeping it safe in Agartha?", choice1: "Share with the surface world", choice1Next: 15, choice2: "Keep it in Agartha", choice2Next: 17, isEnding: false, image: "agartha-city.jpg" },
    { id: 9, text: "You take the orb and leave Kael behind, following the map to Agartha on your own. After passing through a portal, you arrive in a glowing underground forest. A group of Agartha’s inhabitants greets you, curious about the orb. They offer to help you unlock its full power, but warn it could change the world. Do you work with them to unlock the orb, or hide it to protect its secrets?", choice1: "Work with them", choice1Next: 18, choice2: "Hide the orb", choice2Next: 19, isEnding: false, image: "agartha-city.jpg" },
    { id: 10, text: "You follow Lira’s guidance, and she leads you to a hidden underwater cave. Inside, you find a library of crystal tablets engraved with Atlantis’s history. Lira explains, 'This knowledge can heal the world, but it must be shared wisely.' She offers to take you to Agartha, where the tablets can be preserved. Do you go to Agartha with Lira, or return to the surface to share the tablets yourself?", choice1: "Go to Agartha", choice1Next: 20, choice2: "Return to the surface", choice2Next: 16, isEnding: false, image: "atlantis-temple.jpg" },
    { id: 11, text: "You step through the portal to Lemuria’s ruins, arriving in an underwater city of glowing coral and pearl. Fish swim around you, and the pendant keeps you breathing safely. You find a temple with a giant crystal statue of a sea goddess. The statue speaks: 'I am Mara, protector of Lemuria. Help me restore our city’s light.' Do you help Mara with her task, or explore the city for more clues?", choice1: "Help Mara", choice1Next: 21, choice2: "Explore the city", choice2Next: 22, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 12, text: "You ask Tenzin to come with you, and he agrees. Together, you step through the portal to Lemuria. You arrive in a city of shimmering coral, where the pendant lets you breathe underwater. Tenzin points to a glowing tower in the distance. 'That’s the heart of Lemuria,’ he says. ‘We must bring its light back.’ Do you head to the tower with Tenzin, or search the city for other artifacts first?", choice1: "Head to the tower", choice1Next: 23, choice2: "Search for artifacts", choice2Next: 24, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 13, text: "You enter the tunnel, and it slopes downward for what feels like miles. Finally, you emerge in Agartha, a hidden world inside the Earth. Glowing crystals light up a city of golden spires. A friendly guide named Zara greets you, saying, 'Welcome to Agartha. The pendant brought you here to help us.’ She asks you to choose a path: restore Lemuria’s legacy or connect it with Atlantis’s history. Which do you choose?", choice1: "Restore Lemuria", choice1Next: 25, choice2: "Connect with Atlantis", choice2Next: 26, isEnding: false, image: "agartha-city.jpg" },
    { id: 14, text: "You camp outside the cave to prepare, resting and gathering supplies. The next morning, the pendant glows brighter, and you feel ready. You enter the tunnel, which leads to Agartha, a glowing underground world. A guide named Zara welcomes you, explaining that Lemuria’s legacy is here. She offers to show you two paths: one to restore Lemuria, another to connect it with Atlantis. Which path do you take?", choice1: "Restore Lemuria", choice1Next: 25, choice2: "Connect with Atlantis", choice2Next: 26, isEnding: false, image: "agartha-city.jpg" },
    { id: 15, text: "You suggest sharing the orb’s knowledge with the surface world. Kael agrees, and together you return to the surface through a portal. You bring the orb to scientists and historians, who use its knowledge to create new technologies that help the planet—like clean energy and healing medicines. The world celebrates you as a hero, and Atlantis’s legacy lives on in a new age of discovery!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "atlantis-temple.jpg" },
    { id: 16, text: "You decide to return home, taking some artifacts or tablets with you. Back in the Pacific Northwest, you share your discovery with a local museum. They display the items, teaching people about Atlantis or Lemuria’s history. You feel proud of your adventure, even if you didn’t uncover all the secrets. Maybe one day you’ll return to explore more!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "artifact-discovery.jpg" },
    { id: 17, text: "You and Kael decide to keep the orb’s knowledge in Agartha, where it can be safe. The people of Agartha thank you, and you spend time learning their ways, living among their glowing cities. You become a guardian of ancient wisdom, ensuring Atlantis’s secrets are preserved for future generations who might need them.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 18, text: "You work with Agartha’s inhabitants to unlock the orb’s full power. It reveals a map to unite the legacies of Atlantis and Lemuria, showing how their technologies can help the world. You return to the surface, sharing this knowledge with leaders who use it to bring peace and progress. You’re hailed as a bridge between ancient and modern worlds!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 19, text: "You choose to hide the orb to protect its secrets. With the help of Agartha’s people, you place it in a hidden vault deep underground. You feel a sense of peace knowing the knowledge is safe. The inhabitants of Agartha honor you as a protector, and you spend your days exploring their wondrous world, learning their ancient ways.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 20, text: "You travel to Agartha with Lira, arriving in a glowing underground city. The people there welcome you, eager to preserve the crystal tablets. Together, you create a library to store Atlantis’s history, ensuring it’s safe for future generations. Do you stay in Agartha as a guardian, or return to the surface to share what you’ve learned?", choice1: "Stay in Agartha", choice1Next: 27, choice2: "Return to the surface", choice2Next: 28, isEnding: false, image: "agartha-city.jpg" },
    { id: 21, text: "You agree to help Mara restore Lemuria’s light. She asks you to place the pendant in the statue’s hands. When you do, the city glows brighter, and the water sparkles with life. Mara thanks you, saying, 'Lemuria’s legacy can now be shared.’ She offers to take you to Agartha to connect with other ancient worlds. Do you go with her, or stay to rebuild Lemuria?", choice1: "Go to Agartha", choice1Next: 29, choice2: "Stay in Lemuria", choice2Next: 30, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 22, text: "You explore Lemuria’s city, finding a marketplace filled with glowing shells and pearls. A friendly merchant gives you a map to Agartha, saying, 'The pendant will guide you there.’ You thank them and follow the map through a portal, arriving in Agartha’s glowing underground world. A guide asks if you’d like to connect Lemuria’s history with Atlantis’s. Do you agree, or focus on Lemuria’s legacy alone?", choice1: "Connect with Atlantis", choice1Next: 31, choice2: "Focus on Lemuria", choice2Next: 32, isEnding: false, image: "agartha-city.jpg" },
    { id: 23, text: "You and Tenzin head to the glowing tower in Lemuria. Inside, you find a crystal that powers the city. Tenzin says, 'We must channel the pendant’s energy to restore it.’ Together, you activate the crystal, and Lemuria shines brighter than ever. Tenzin suggests traveling to Agartha to unite Lemuria’s light with other ancient worlds. Do you go with him, or stay to protect Lemuria?", choice1: "Go to Agartha", choice1Next: 29, choice2: "Stay in Lemuria", choice2Next: 30, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 24, text: "You search Lemuria for artifacts, finding a chest of glowing pearls. A holographic guardian appears, saying, 'These pearls hold Lemuria’s wisdom. Take them to Agartha to keep them safe.’ You agree and follow a portal to Agartha, where the inhabitants welcome you. Do you share the pearls with the surface world, or keep them in Agartha for safety?", choice1: "Share with the surface", choice1Next: 33, choice2: "Keep in Agartha", choice2Next: 34, isEnding: false, image: "agartha-city.jpg" },
    { id: 25, text: "You choose to restore Lemuria’s legacy in Agartha. Zara leads you to a temple where Lemuria’s survivors live. They ask you to place the pendant in a pedestal to bring back their city’s light. You do, and the temple glows with energy, reviving their culture. Do you stay to help them rebuild, or return to the surface to share their story?", choice1: "Stay and rebuild", choice1Next: 35, choice2: "Return to the surface", choice2Next: 36, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 26, text: "You choose to connect Lemuria with Atlantis’s history. Zara takes you to a council of Agartha’s elders, who use the pendant to reveal a shared history between the two civilizations. They ask you to decide: share this knowledge with the world, or seal it away to prevent misuse. What do you choose?", choice1: "Share with the world", choice1Next: 37, choice2: "Seal it away", choice2Next: 38, isEnding: false, image: "agartha-city.jpg" },
    { id: 27, text: "You decide to stay in Agartha as a guardian of the crystal tablets. The people teach you their ways, and you spend your days exploring the underground world, marveling at its glowing cities and ancient wonders. You feel a deep connection to Atlantis’s legacy, knowing you’ve helped preserve it for generations to come.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 28, text: "You return to the surface with the knowledge of the tablets. You share Atlantis’s history with the world, inspiring new discoveries in science and culture. People thank you for bringing the past to life, and you feel proud to have connected humanity with its ancient roots.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "atlantis-temple.jpg" },
    { id: 29, text: "You travel to Agartha with Mara (or Tenzin), arriving in a glowing underground city. The elders there ask you to unite Lemuria’s light with Atlantis’s knowledge, creating a new legacy. You work together, and the result is a beautiful harmony of ancient wisdom. Do you share this with the surface world, or become a guardian of Agartha?", choice1: "Share with the surface", choice1Next: 37, choice2: "Become a guardian", choice2Next: 39, isEnding: false, image: "agartha-city.jpg" },
    { id: 30, text: "You choose to stay in Lemuria, helping to rebuild its glowing city. With Mara (or Tenzin), you restore the coral towers and bring life back to the underwater world. Lemuria becomes a sanctuary of peace, and you feel fulfilled knowing you’ve helped a lost civilization shine again.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "lemuria-portal.jpg" },
    { id: 31, text: "You agree to connect Lemuria’s history with Atlantis’s. In Agartha, you work with the elders to combine their knowledge, creating a new understanding of the ancient world. They ask you to choose: share this wisdom with the surface, or seal it away to protect it. What do you decide?", choice1: "Share with the surface", choice1Next: 37, choice2: "Seal it away", choice2Next: 38, isEnding: false, image: "agartha-city.jpg" },
    { id: 32, text: "You focus on Lemuria’s legacy alone. The people of Agartha help you rebuild a temple to honor Lemuria, using the pendant to light it up. You feel a deep connection to this ancient world. Do you stay to protect Lemuria’s legacy, or return to the surface to share its story?", choice1: "Stay and protect", choice1Next: 35, choice2: "Return to the surface", choice2Next: 36, isEnding: false, image: "lemuria-portal.jpg" },
    { id: 33, text: "You share the pearls with the surface world, returning through a portal. Scientists study them, discovering new ways to clean the oceans and grow food. The world thanks you for bringing Lemuria’s wisdom to life, and you feel proud to have made a difference for the planet!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "lemuria-portal.jpg" },
    { id: 34, text: "You keep the pearls in Agartha for safety. The inhabitants build a special vault to protect them, and you help guard their wisdom. You spend your days in Agartha, learning from its people and feeling honored to protect Lemuria’s legacy for the future.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 35, text: "You stay in Agartha to help rebuild Lemuria’s legacy. With the people there, you create a new city filled with glowing coral and pearls, honoring the past. You feel a deep sense of purpose, knowing you’ve helped a lost civilization live on in a hidden world.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "lemuria-portal.jpg" },
    { id: 36, text: "You return to the surface to share Lemuria’s story. You write a book about your adventure, inspiring people to care for the oceans and learn from the past. Your story spreads hope, and you’re celebrated as an explorer who brought Lemuria’s light to the world!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "lemuria-portal.jpg" },
    { id: 37, text: "You choose to share the combined wisdom of Atlantis and Lemuria with the surface world. Back home, you work with experts to use this knowledge for good—creating clean energy, healing medicines, and more. The world enters a new era of peace and discovery, thanks to you!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "atlantis-temple.jpg" },
    { id: 38, text: "You decide to seal the combined knowledge away to prevent misuse. In Agartha, you help the elders create a hidden vault, ensuring the secrets are safe. You feel proud knowing you’ve protected these ancient wonders for a time when the world is ready.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 39, text: "You become a guardian of Agartha, staying in the underground world to protect its wonders. You learn from the elders, explore glowing cities, and feel a deep connection to the ancient past. Your role ensures that Atlantis and Lemuria’s legacies live on safely.", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" },
    { id: 40, text: "You unite the legacies of Atlantis, Lemuria, and Agartha, creating a new future. Returning to the surface, you share their wisdom, sparking a global renaissance of peace, technology, and culture. You’re remembered as the explorer who brought the ancient world into the modern age!", choice1: "", choice1Next: 0, choice2: "", choice2Next: 0, isEnding: true, image: "agartha-city.jpg" }
];

let currentSegment = 1;

function updateScreen() {
    const segment = storySegments.find(s => s.id === currentSegment);
    document.getElementById("story-text").innerText = segment.text;
    const choice1Btn = document.getElementById("choice1");
    const choice2Btn = document.getElementById("choice2");
    const restartBtn = document.getElementById("restart");
    const storyImage = document.getElementById("story-image");

    // Update image with explicit path and error handling
    if (segment.image) {
        storyImage.src = `./${segment.image}`; // e.g., "./artifact-discovery.jpg"
        storyImage.alt = `Image for segment ${segment.id}`;
        console.log(`Attempting to load image: ./${segment.image}`);
        storyImage.onerror = () => {
            console.error(`Failed to load image: ./${segment.image}`);
            storyImage.src = "";
            storyImage.alt = "Image not found";
        };
    } else {
        storyImage.src = "";
        storyImage.alt = "";
    }

    if (segment.isEnding) {
        choice1Btn.style.display = "none";
        choice2Btn.style.display = "none";
        restartBtn.style.display = "block";
    } else {
        choice1Btn.style.display = "block";
        choice1Btn.innerText = segment.choice1;
        choice2Btn.style.display = "block";
        choice2Btn.innerText = segment.choice2;
        restartBtn.style.display = "none";
    }
}

// ... rest of the script ...
updateScreen();// Add event listeners for choices and restart
document.getElementById("choice1").onclick = function () {
    const segment = storySegments.find(s => s.id === currentSegment);
    if (segment && segment.choice1Next) {
        currentSegment = segment.choice1Next;
        updateScreen();
    }
};

document.getElementById("choice2").onclick = function () {
    const segment = storySegments.find(s => s.id === currentSegment);
    if (segment && segment.choice2Next) {
        currentSegment = segment.choice2Next;
        updateScreen();
    }
};

document.getElementById("restart").onclick = function () {
    currentSegment = 1;
    updateScreen();
};